spring.application.name=user-service
server.port=8081
spring.data.mongodb.uri=mongodb+srv://tanishcse22_db_user:tanish00@cluster0.ssdrnk2.mongodb.net/shopnest_users?retryWrites=true&w=majority&appName=Cluster0
jwt.secret=shopnest-super-secret-key-minimum-256-bits-long
