spring.application.name=recommendation-service
server.port=8085
spring.data.mongodb.uri=mongodb+srv://tanishcse22_db_user:tanish00@cluster0.ssdrnk2.mongodb.net/shopnest_recommendations?retryWrites=true&w=majority&appName=Cluster0
services.product.url=http://localhost:8082
