spring.application.name=recommendation-service
server.port=8085
spring.data.mongodb.uri=mongodb+srv://tanishcse22_db_user:shopnest123@cluster0.ksy7y8f.mongodb.net/shopnest_recommendations?retryWrites=true&w=majority&appName=Cluster0
services.product.url=http://localhost:8082
