spring.application.name=cart-service
server.port=8083
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/shopnest_cart?retryWrites=true&w=majority
services.product.url=http://localhost:8082
