spring.application.name=cart-service
server.port=8083
spring.data.mongodb.uri=mongodb+srv://tanishcse22_db_user:shopnest123@cluster0.ksy7y8f.mongodb.net/shopnest_cart?retryWrites=true&w=majority&appName=Cluster0
services.product.url=http://localhost:8082
